marius top screen stuff
Adex-8x/mm5-patches pull request #1
Opened 2024-06-25 16:39 UTC by marius851000

Allow to display 16bpp images on top screen, and draw stuff in realtime following instruction.
Stuff I made for last hackjam but went unused (ported to US), only lightly tested (but the hackjam stuff was well tested).

Dunno if I’ll make use of it.

2024-06-25 17:34 UTC, Adex-8x commented
Thank you so much! I'll check everything out soon, though first impressions:
- I assume the Top Screen has to be set into mode 0 by `back2_SetMode(0);`, which is alright, but might want to be noted somewhere.
- Your special processes do work on hardware/MelonDS, but after repeated use alongside `message_Menu(100);`, the game does seem to crash due to what I assume to be some memory-related issue? This might actually be a fault of how I handled the menu management, but I'll have to test further.
For reference, the script I tested with is:
```
def 0 {
    back2_SetMode(0);
    screen_FadeIn(1, 0);
    screen2_FadeIn(1, 0);
    ProcessSpecial(110, 1, 0);
    ProcessSpecial(PROCESS_SPECIAL_KEY_WAIT_PRESS, 0, 0);
    ProcessSpecial(111, 0, 0);
    ProcessSpecial(PROCESS_SPECIAL_KEY_WAIT_PRESS, 0, 0);
    ProcessSpecial(112, 1, 0);
    ProcessSpecial(PROCESS_SPECIAL_KEY_WAIT_PRESS, 0, 0);
    ProcessSpecial(111, 0, 0);
    ProcessSpecial(PROCESS_SPECIAL_KEY_WAIT_PRESS, 0, 0);
    end;
}
```
After this script runs twice, attempting to select an option from `message_Menu(100);` crashes the game.

2024-06-25 18:36 UTC, Adex-8x requested changes
Found the source of the crash, it's nothing tricky to fix yay

2024-06-25 18:36 UTC, Adex-8x commented on src/drawing.c
> +    FileOpen(&DRAWING_STATE.file, filepath);
Need to call [`FileInit`](https://github.com/UsernameFodder/pmdsky-debug/blob/4f361d8590e4ba28306670a20046e1c6ba38fa59/symbols/arm9/libs.yml#L2098-L2108) or [`FileInitVeneer`](https://github.com/UsernameFodder/pmdsky-debug/blob/4f361d8590e4ba28306670a20046e1c6ba38fa59/symbols/arm9.yml#L932-L944) prior to file opening.

2024-06-25 18:36 UTC, Adex-8x commented on src/display_image.c
> +    FileOpen(&file, filepath);
Need to call [`FileInit`](https://github.com/UsernameFodder/pmdsky-debug/blob/4f361d8590e4ba28306670a20046e1c6ba38fa59/symbols/arm9/libs.yml#L2098-L2108) or [`FileInitVeneer`](https://github.com/UsernameFodder/pmdsky-debug/blob/4f361d8590e4ba28306670a20046e1c6ba38fa59/symbols/arm9.yml#L932-L944) prior to file opening.

2024-06-25 18:36 UTC, Adex-8x commented on src/special_processes.c
> +    // Return top screen to what it was before it was set by 110 or 111
Do you mean "set by 110 or 112"?

2024-06-26 15:40 UTC, marius851000 commented
Thanks a lot. Never met that crash situation before, but I still wonder how I could have left such an uninitialized variable error happen (that’s a joke. I totally knew how that happened, and why Rust is a better language than C, but that it’s not the most appropriate in this context).

2024-06-26 15:45 UTC, Adex-8x approved these changes
Thanks again! These are really cool features, hype

2024-06-26 15:45 UTC, merged

2024-06-26 15:46 UTC, marius851000 commented
Next, you’ll have a touchscreen trail following the cursor with 3d. (also thinking about just throwing my custom textbox border drawing routine in the mix. It’s cool all you can do with the 3D engine)